### ISSUE TITLE
Glyph section count of Phone1's central glyph

### ISSUE THREAD

**Issue by JayKay135** [Nothing-Developer-Programme/Glyph-Developer-Kit#10]
I do not own a physically phone 1 myself and cannot test this.
The documentation is kind of misleading here: There are four indices (2-5) assigned for the central glyph of phone 1: C1-C4
However, in the image there is only C1 written.
Is it now one central glyph, or are there 4 sections that can be triggered independently?

**Comment by SebiAi** [comment]
There are 4 independent sections in the central Glyph on the Phone (1). But I don't know if you can access them via the `GlyphFrame.Builder`.
If the `GlyphFrame.Builder` route does not work and you still want to use them you can use the undocumented `GlyphManager.setFrameColors()` function.

Source: Nothing Phone (1) user who used the *Glyph Developer Kit* once when it first came out.

**Comment by JayKay135** [comment]
Alright thank you. 
One last additional question: Are those four sections equally split or is it like the top portion, the left straight line, bottom round part and the right line. 
And do you happen to know where the start of the glyph is. 
So is C1 the bottom right or the top left.

**Comment by SebiAi** [comment]
I think this video should answer all your questions :wink:

https://github.com/Nothing-Developer-Programme/Glyph-Developer-Kit/assets/41116921/6c41fc45-60a1-4206-83a7-2f50ecb5bc52

**Comment by JayKay135** [comment]
Thank you so much. Precisely what I needed
